on:
  push:
  pull_request:
  workflow_dispatch:


jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: microsoft/setup-msbuild@v2
    - run: nuget restore Onitool.sln
    - run: msbuild Onitool.sln /p:Configuration=Release

    - uses: actions/upload-artifact@v4
      with:
        name: WinFormsApp
        path: |
          bin/Release
